import { getCarrierByCode } from "../carriers";
import { officialTrackingUrls } from "../carriers";
import type { TrackingResult } from "../types";

const DEMO_CONTAINERS: Record<string, TrackingResult> = {
  MSKU3900520: {
    kind: "container",
    query: "MSKU3900520",
    source: "demo",
    carrier: getCarrierByCode("MAERSK"),
    containerNumber: "MSKU3900520",
    billOfLading: "MAEU918273645",
    containerType: "40' High Cube",
    status: "Đang trên biển (Vessel departed)",
    origin: "Cát Lái, Hồ Chí Minh, VN",
    originTerminal: "Cát Lái Terminal",
    destination: "Rotterdam, NL",
    destinationTerminal: "ECT Delta",
    loadingPort: "Vũng Tàu (Cái Mép), VN",
    dischargingPort: "Rotterdam, NL",
    atd: "2026-08-12T09:20:00Z",
    eta: "2026-09-18T06:00:00Z",
    lastLocation: "Singapore, SG — transshipment",
    nextLocation: "Rotterdam, NL",
    vessel: {
      name: "MAERSK ESSEN",
      voyage: "626W",
      imo: "9456783",
      mmsi: "219000000",
      lat: 5.82,
      lng: 88.41,
      speed: 18.4,
      heading: 275,
      destination: "NLRTM",
      flag: "DK",
      lastPositionAt: "2026-08-21T08:10:00Z",
      eta: "2026-09-18T06:00:00Z",
    },
    events: [
      {
        time: "2026-08-02T04:10:00Z",
        status: "Gate in empty",
        location: "Cát Lái, Hồ Chí Minh",
        vessel: null,
        voyage: null,
        isActual: true,
      },
      {
        time: "2026-08-05T16:40:00Z",
        status: "Gate in full (export)",
        location: "Cát Lái, Hồ Chí Minh",
        vessel: null,
        voyage: null,
        isActual: true,
      },
      {
        time: "2026-08-08T11:05:00Z",
        status: "Loaded on vessel",
        location: "Cái Mép, Vũng Tàu",
        vessel: "MAERSK SELETAR",
        voyage: "624N",
        isActual: true,
      },
      {
        time: "2026-08-12T09:20:00Z",
        status: "Vessel departed",
        location: "Cái Mép, Vũng Tàu",
        vessel: "MAERSK SELETAR",
        voyage: "624N",
        isActual: true,
      },
      {
        time: "2026-08-15T22:00:00Z",
        status: "Vessel arrived",
        location: "Singapore",
        vessel: "MAERSK SELETAR",
        voyage: "624N",
        isActual: true,
      },
      {
        time: "2026-08-17T03:30:00Z",
        status: "Transshipment — loaded",
        location: "PSA Singapore",
        vessel: "MAERSK ESSEN",
        voyage: "626W",
        isActual: true,
      },
      {
        time: "2026-08-17T18:10:00Z",
        status: "Vessel departed",
        location: "Singapore",
        vessel: "MAERSK ESSEN",
        voyage: "626W",
        isActual: true,
      },
      {
        time: "2026-09-18T06:00:00Z",
        status: "ETA discharge",
        location: "Rotterdam, NL",
        vessel: "MAERSK ESSEN",
        voyage: "626W",
        isActual: false,
      },
    ],
    officialUrls: officialTrackingUrls("MSKU3900520", "container", getCarrierByCode("MAERSK")),
    lastUpdated: "2026-08-21T08:10:00Z",
  },
  MSCU7349821: {
    kind: "container",
    query: "MSCU7349821",
    source: "demo",
    carrier: getCarrierByCode("MSC"),
    containerNumber: "MSCU7349821",
    billOfLading: "MEDUHP882210",
    containerType: "20' Dry",
    status: "Đã dỡ hàng tại cảng đến",
    origin: "Shanghai, CN",
    originTerminal: "Yangshan Deep Water Port",
    destination: "Hải Phòng, VN",
    destinationTerminal: "Nam Đình Vũ",
    loadingPort: "Shanghai, CN",
    dischargingPort: "Hải Phòng, VN",
    atd: "2026-08-01T14:00:00Z",
    eta: "2026-08-18T07:00:00Z",
    lastLocation: "Hải Phòng, VN",
    nextLocation: "Gate out empty",
    vessel: {
      name: "MSC LENA",
      voyage: "YF432A",
      imo: "9842061",
      mmsi: "636018000",
      lat: 20.86,
      lng: 106.68,
      speed: 0,
      heading: 90,
      destination: "VNHPH",
      flag: "LR",
      navStatus: "Moored",
      lastPositionAt: "2026-08-20T02:00:00Z",
    },
    events: [
      {
        time: "2026-07-28T09:00:00Z",
        status: "Gate in full",
        location: "Shanghai, CN",
        vessel: null,
        voyage: null,
        isActual: true,
      },
      {
        time: "2026-08-01T14:00:00Z",
        status: "Vessel departed",
        location: "Shanghai, CN",
        vessel: "MSC LENA",
        voyage: "YF432A",
        isActual: true,
      },
      {
        time: "2026-08-18T07:20:00Z",
        status: "Vessel arrived",
        location: "Hải Phòng, VN",
        vessel: "MSC LENA",
        voyage: "YF432A",
        isActual: true,
      },
      {
        time: "2026-08-19T11:45:00Z",
        status: "Discharged",
        location: "Nam Đình Vũ, Hải Phòng",
        vessel: "MSC LENA",
        voyage: "YF432A",
        isActual: true,
      },
    ],
    officialUrls: officialTrackingUrls("MSCU7349821", "container", getCarrierByCode("MSC")),
    lastUpdated: "2026-08-20T02:00:00Z",
  },
  CMAU2198470: {
    kind: "container",
    query: "CMAU2198470",
    source: "demo",
    carrier: getCarrierByCode("CMA_CGM"),
    containerNumber: "CMAU2198470",
    billOfLading: "CMDUVN5566123",
    containerType: "40' High Cube Reefer",
    status: "Loaded — chờ tàu rời Cái Mép",
    origin: "Cái Mép, VN",
    destination: "Los Angeles, US",
    loadingPort: "Cái Mép, VN",
    dischargingPort: "Los Angeles, US",
    atd: null,
    eta: "2026-09-22T16:00:00Z",
    lastLocation: "Cái Mép International Terminal",
    nextLocation: "Los Angeles, US",
    vessel: {
      name: "CMA CGM MARCO POLO",
      voyage: "0FL8EW",
      imo: "9454436",
      lat: 10.49,
      lng: 107.03,
      speed: 0.2,
      destination: "USLAX",
    },
    events: [
      {
        time: "2026-08-18T08:00:00Z",
        status: "Gate in full",
        location: "Cái Mép, VN",
        vessel: null,
        voyage: null,
        isActual: true,
      },
      {
        time: "2026-08-20T21:30:00Z",
        status: "Loaded on vessel",
        location: "Cái Mép, VN",
        vessel: "CMA CGM MARCO POLO",
        voyage: "0FL8EW",
        isActual: true,
      },
      {
        time: "2026-08-22T04:00:00Z",
        status: "ETD — vessel departure",
        location: "Cái Mép, VN",
        vessel: "CMA CGM MARCO POLO",
        voyage: "0FL8EW",
        isActual: false,
      },
    ],
    officialUrls: officialTrackingUrls("CMAU2198470", "container", getCarrierByCode("CMA_CGM")),
    lastUpdated: "2026-08-21T01:00:00Z",
  },
};

const DEMO_BILLS: Record<string, TrackingResult> = {
  MAEU918273645: {
    ...DEMO_CONTAINERS.MSKU3900520,
    kind: "bl",
    query: "MAEU918273645",
    billOfLading: "MAEU918273645",
    relatedContainers: ["MSKU3900520", "MSKU4011283", "SUDU8871201"],
    officialUrls: officialTrackingUrls("MAEU918273645", "bl", getCarrierByCode("MAERSK")),
  },
  MEDUHP882210: {
    ...DEMO_CONTAINERS.MSCU7349821,
    kind: "bl",
    query: "MEDUHP882210",
    billOfLading: "MEDUHP882210",
    relatedContainers: ["MSCU7349821", "MEDU3288655"],
    officialUrls: officialTrackingUrls("MEDUHP882210", "bl", getCarrierByCode("MSC")),
  },
};

const DEMO_VESSELS: Record<string, TrackingResult> = {
  "MAERSK ESSEN": vesselResult("MAERSK ESSEN", {
    name: "MAERSK ESSEN",
    imo: "9456783",
    mmsi: "219000000",
    lat: 5.82,
    lng: 88.41,
    speed: 18.4,
    heading: 275,
    destination: "NLRTM via SGSIN",
    flag: "DK",
    lastPositionAt: "2026-08-21T08:10:00Z",
    eta: "2026-09-18T06:00:00Z",
  }),
  "9456783": vesselResult("9456783", {
    name: "MAERSK ESSEN",
    imo: "9456783",
    mmsi: "219000000",
    lat: 5.82,
    lng: 88.41,
    speed: 18.4,
    heading: 275,
    destination: "NLRTM",
    flag: "DK",
    lastPositionAt: "2026-08-21T08:10:00Z",
  }),
  "EVER GIVEN": vesselResult("EVER GIVEN", {
    name: "EVER GIVEN",
    imo: "9811000",
    mmsi: "353136000",
    lat: 1.27,
    lng: 103.78,
    speed: 0.1,
    heading: 180,
    destination: "SGSIN",
    flag: "PA",
    navStatus: "At anchor",
    lastPositionAt: "2026-08-21T07:40:00Z",
  }),
  "9811000": vesselResult("9811000", {
    name: "EVER GIVEN",
    imo: "9811000",
    mmsi: "353136000",
    lat: 1.27,
    lng: 103.78,
    speed: 0.1,
    destination: "SGSIN",
    flag: "PA",
  }),
  "MSC LENA": vesselResult("MSC LENA", {
    name: "MSC LENA",
    imo: "9842061",
    mmsi: "636018000",
    lat: 20.86,
    lng: 106.68,
    speed: 0,
    destination: "VNHPH",
    flag: "LR",
    navStatus: "Moored",
  }),
};

function vesselResult(query: string, vessel: TrackingResult["vessel"]): TrackingResult {
  return {
    kind: "vessel",
    query,
    source: "demo",
    carrier: null,
    status: vessel?.navStatus || (vessel?.speed && vessel.speed > 1 ? "Under way" : "Stationary"),
    destination: vessel?.destination ?? null,
    eta: vessel?.eta ?? null,
    vessel,
    events: [
      {
        time: vessel?.lastPositionAt ?? null,
        status: "AIS position",
        location: vessel?.destination ?? null,
        vessel: vessel?.name ?? null,
        voyage: null,
        isActual: true,
      },
    ],
    officialUrls: officialTrackingUrls(vessel?.name || query, "vessel"),
    lastUpdated: vessel?.lastPositionAt ?? null,
  };
}

export const DEMO_HINTS = {
  containers: ["MSKU3900520", "MSCU7349821", "CMAU2198470"],
  bills: ["MAEU918273645", "MEDUHP882210"],
  vessels: ["MAERSK ESSEN", "EVER GIVEN", "MSC LENA"],
};

export function getDemoResult(
  kind: "container" | "bl" | "vessel",
  normalized: string,
): TrackingResult | null {
  const key = normalized.toUpperCase();
  if (kind === "container") return DEMO_CONTAINERS[key] ?? null;
  if (kind === "bl") return DEMO_BILLS[key] ?? null;
  return DEMO_VESSELS[key] ?? null;
}
